# Zadanie VIII

In [ ]:
conda install pandas

In [ ]:
conda install scikit-learn

In [ ]:
conda install matplotlib

In [2]:
import pandas as pd

In [22]:
from sklearn.feature_extraction.text import TfidfTransformer

In [23]:
import numpy as np

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
import matplotlib.pyplot as plt

In [70]:
import string

### Zadanie

In [3]:
data = pd.read_csv('https://www.fizyka.umk.pl/~grochu/wdm/files/spam_train.csv')

In [12]:
spam_train = data.replace('ham', 0)

In [13]:
spam_train = spam_train.replace('spam', 1)

In [20]:
spam_train

Class                                                SMS
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
3995      0  We'll you pay over like  &lt;#&gt; yrs so its ...
3996      1  Bored housewives! Chat n date now! 0871750.77....
3997      1  We tried to call you re your reply to our sms ...
3998      0                  K...k...when will you give treat?
3999      1  This is the 2nd time we have tried to contact ...

[4000 rows x 2 columns]

In [34]:
words_train = spam_train.iloc[:,1]

In [35]:
words_train

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
3995    We'll you pay over like  &lt;#&gt; yrs so its ...
3996    Bored housewives! Chat n date now! 0871750.77....
3997    We tried to call you re your reply to our sms ...
3998                    K...k...when will you give treat?
3999    This is the 2nd time we have tried to contact ...
Name: SMS, Length: 4000, dtype: object

In [52]:
words_train = [w.lower() for w in words_train]

In [68]:
stop_words =['i','me','my','myself','we','our','ours','ourselves','you','your','yours','yourself',
            'yourselves','he','him','his','himself','she','her','hers','herself','it','its','itself',
            'they','them','their','theirs','themselves','what','which','who','whom','this','that',
            'these','those','am','is','are','was','were','be','been','being','have','has','had',
            'having','do','does','did','doing','a','an','the','and','but','if','or','because','as',
            'until','while','of','at','by','for','with','about','against','between','into','through',
            'during','before','after','above','below','to','from','up','down','in','out','on','off',
            'over','under','again','further','then','once','here','there','when','where','why','how',
            'all','any','both','each','few','more','most','other','some','such','no','nor','not',
            'only','own','same','so','than','too','very','s','t','can','will','just','don','should',
            'now','uses','use','using','used','one','also']

In [56]:
words = []
for row in words_train:
    for word in row.split():
        if word not in stop_words:
            words.append(word)
            
words = set(words)

print('Ilość unikatowych słów: ', len(words))

Ilość unikatowych słów:  10904


In [71]:
words_train_np = [''.join(c for c in s if c not in string.punctuation) for s in words_train]

## No punctuation

In [72]:
words_train_np

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005 text fa to 87121 to receive entry questionstd txt ratetcs apply 08452810075over18s',
 'u dun say so early hor u c already then say',
 'nah i dont think he goes to usf he lives around here though',
 'freemsg hey there darling its been 3 weeks now and no word back id like some fun you up for it still tb ok xxx std chgs to send å£150 to rcv',
 'even my brother is not like to speak with me they treat me like aids patent',
 'as per your request melle melle oru minnaminunginte nurungu vettam has been set as your callertune for all callers press 9 to copy your friends callertune',
 'winner as a valued network customer you have been selected to receivea å£900 prize reward to claim call 09061701461 claim code kl341 valid 12 hours only',
 'had your mobile 11 months or more u r entitled to update

In [78]:
vocabulary = {}
for row in words_train_np:
    for word in row.split():
        if word not in stop_words:
            if word not in vocabulary:
                vocabulary[word] = 1
            else:
                vocabulary[word] += 1
                
words = vocabulary.keys()

print('Ilość unikatowych słów: ', len(words))

Ilość unikatowych słów:  7822


In [79]:
word2id = {}

for i, word in enumerate(words):
    word2id[word] = i
    print(word2id[word], word)

0 go
1 jurong
2 point
3 crazy
4 available
5 bugis
6 n
7 great
8 world
9 la
10 e
11 buffet
12 cine
13 got
14 amore
15 wat
16 ok
17 lar
18 joking
19 wif
20 u
21 oni
22 free
23 entry
24 2
25 wkly
26 comp
27 win
28 fa
29 cup
30 final
31 tkts
32 21st
33 may
34 2005
35 text
36 87121
37 receive
38 questionstd
39 txt
40 ratetcs
41 apply
42 08452810075over18s
43 dun
44 say
45 early
46 hor
47 c
48 already
49 nah
50 dont
51 think
52 goes
53 usf
54 lives
55 around
56 though
57 freemsg
58 hey
59 darling
60 3
61 weeks
62 word
63 back
64 id
65 like
66 fun
67 still
68 tb
69 xxx
70 std
71 chgs
72 send
73 å£150
74 rcv
75 even
76 brother
77 speak
78 treat
79 aids
80 patent
81 per
82 request
83 melle
84 oru
85 minnaminunginte
86 nurungu
87 vettam
88 set
89 callertune
90 callers
91 press
92 9
93 copy
94 friends
95 winner
96 valued
97 network
98 customer
99 selected
100 receivea
101 å£900
102 prize
103 reward
104 claim
105 call
106 09061701461
107 code
108 kl341
109 valid
110 12
111 hours
112 mobile
113 11


In [101]:
bag = np.zeros((len(words_train_np), len(words)), dtype=np.int32)

for i, row in enumerate(words_train_np):
    for word in row.split():
        if word not in stop_words:
            bag[i, word2id[word]] += 1

print(bag)

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 1]]


### Regresja logistyczna

In [102]:
from sklearn.linear_model import LogisticRegression

In [106]:
clf = LogisticRegression()

In [107]:
clf = clf.fit(bag, spam_train.iloc[:,0])

In [108]:
data2 = pd.read_csv('https://www.fizyka.umk.pl/~grochu/wdm/files/spam_test.csv')
spam_test = data2.replace('ham', 0)
spam_test = spam_test.replace('spam', 1)

In [118]:
import re
def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)             # usuwanie znaczników HTML
    text = re.sub('[\W]+', ' ', text.lower())      # pozbywamy się wszystkich znaków, które nie są literami
    return text

In [137]:
datav1 = data

In [138]:
datav1 = datav1.iloc[:,1].apply(preprocessor)

In [146]:
datav1

0       go until jurong point crazy available only in ...
1                                ok lar joking wif u oni 
2       free entry in 2 a wkly comp to win fa cup fina...
3            u dun say so early hor u c already then say 
4       nah i don t think he goes to usf he lives arou...
                              ...                        
3995    we ll you pay over like lt gt yrs so its not t...
3996    bored housewives chat n date now 0871750 77 11...
3997    we tried to call you re your reply to our sms ...
3998                        k k when will you give treat 
3999    this is the 2nd time we have tried to contact ...
Name: SMS, Length: 4000, dtype: object

In [153]:
datav1.iloc[[]]

SyntaxError: invalid syntax (<ipython-input-153-3a652c92e82c>, line 1)

In [140]:
X_train = datav1.loc[:,1]

IndexingError: Too many indexers

In [ ]:
tfidf = TfidfVectorizer(stop_words='english')

X_tfidf_train = tfidf.fit_transform()